//
// Created by swaggan on 21.07.21.
//

#ifndef CMAKE_PROJECT_EXERCISE_LINE_SEGMENT_INTERSECTION_H
#define CMAKE_PROJECT_EXERCISE_LINE_SEGMENT_INTERSECTION_H

#endif //CMAKE_PROJECT_EXERCISE_LINE_SEGMENT_INTERSECTION_H
