//
// Created by swaggan on 04.05.21.
//

#ifndef EXERCISE_1_2_PALINDROME_CHECKER_PALINDROME_CHECKER_H
#define EXERCISE_1_2_PALINDROME_CHECKER_PALINDROME_CHECKER_H

bool isPalindrome(std::string line);

#endif //EXERCISE_1_2_PALINDROME_CHECKER_PALINDROME_CHECKER_H
